#!/bin/bash
#run with $ yes | script
echo -e \\nRUNNING FRESH PACKAGES INSTALLATION
echo -e \\nCleaning Cache.....................................
sudo apt-get clean 

# Add PPAs
#echo -e \\nAdding PPAs.......................................\\n
#sudo add-apt-repository -y ppa:kupfer-team/ppa ppa:numix/ppa ppa:webupd8team/sublime-text-3
 

# System update
echo -e \\nUpdating List......................................\\n
sudo apt-get update 

echo -e \\nUpgrading packages.................................\\n
sudo apt-get -y upgrade 

echo Updating Distribution....................................\\n
sudo apt-get -y dist-upgrade 


# Installing Essential Packages

sudo yes | curl -sL https://raw.githubusercontent.com/sushilshinde/config/master/linux/ubuntu/modules/install/base | sudo -E bash -

#Installing NodeJS

sudo yes | curl -sL https://raw.githubusercontent.com/sushilshinde/config/master/linux/ubuntu/modules/install/nodejs | sudo -E bash -

#Installling Extras
echo -e \\nInstalling Extras...............................\\n
sudo yes | curl -sL https://raw.githubusercontent.com/sushilshinde/config/master/linux/ubuntu/modules/install/extras | sudo -E bash -

echo -e \\nCleaning...........................................\\n
sudo apt-get -y purge
